import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/components/Providers";
import { fustatSans } from "./fonts";

export const metadata: Metadata = {
  title: "Miau Cofrin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fustatSans.variable} antialiased`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
